- README.md
- custom_components/fritzbox_tools/__init__.py
- custom_components/fritzbox_tools/switch.py
- info.md
I tried implementing the port switches in the same manner as the guest wifi switch. I hope it works that way.
Not working yet:
1. ipv6 toggle of ports (probably will never)
2. automatic discovery of devices ip. Till now: only  manual setting in configuration.yaml
3. entity_id not set, only names set.
4. Opened ports are only discovered when component is loaded
Debugging probably still necessary
Fixes #9
> Port Switch

- custom_components/fritzbox_tools/__init__.py
- custom_components/fritzbox_tools/manifest.json
go from 0.8.2 to 0.8.4
required by https://github.com/home-assistant/home-assistant/pull/27698
> Update fritzconnection to 0.8.4

- custom_components/fritzbox_tools/switch.py
> generalizes the connectiontype

- README.md
- custom_components/fritzbox_tools/__init__.py
- custom_components/fritzbox_tools/manifest.json
- custom_components/fritzbox_tools/sensor.py
- custom_components/fritzbox_tools/switch.py
- info.md
See issue #6.
Needs debugging and testing now
> Device Profile Switch

- custom_components/fritzbox_tools/switch.py
Previously we wouldn't create any profile switches as soon as there were duplicated host names. 
I tried to improve this, what do you think @AaronDavidSchneider?
This change is tested on my setup and works fine.
Related #17 and #6
> Improve handling of duplicated host names when creating profile switches

- custom_components/fritzbox_tools/__init__.py
- custom_components/fritzbox_tools/sensor.py
- custom_components/fritzbox_tools/switch.py
Solves issue #1 
Tested with my configuration and works.
Edit:
- Setup of component not speeded up yet
- fixes state jiggeling, if multiple device profiles are triggered simulataniously
> Make async

- custom_components/fritzbox_tools/switch.py
simple fix for #39
Based on answer of @dennis84de in https://github.com/mammuth/ha-fritzbox-tools/issues/36#issuecomment-554068607.
> guestwifi fix for non dualband routers

- README.md
- custom_components/fritzbox_tools/.translations/de.json
- custom_components/fritzbox_tools/.translations/en.json
- custom_components/fritzbox_tools/__init__.py
- custom_components/fritzbox_tools/config_flow.py
- custom_components/fritzbox_tools/const.py
- custom_components/fritzbox_tools/manifest.json
- custom_components/fritzbox_tools/sensor.py
- custom_components/fritzbox_tools/strings.json
- custom_components/fritzbox_tools/switch.py
- info.md
First try to implement a config flow.
Not working yet!
Edit: This is going to be a larger pull request. Many things need to be rewritten for this to work.
> Config Flow

- custom_components/fritzbox_tools/__init__.py
- custom_components/fritzbox_tools/binary_sensor.py
- custom_components/fritzbox_tools/config_flow.py
- custom_components/fritzbox_tools/const.py
- custom_components/fritzbox_tools/switch.py
> Format code with black

- custom_components/fritzbox_tools/__init__.py
not sure if this problem really is related to #55. However, I found this relict in the code. We should change it, because profile_on is now not None by default anymore (since some time ago).
> fix issue #55?!

- custom_components/fritzbox_tools/.translations/de.json
- custom_components/fritzbox_tools/.translations/en.json
- custom_components/fritzbox_tools/__init__.py
- custom_components/fritzbox_tools/config_flow.py
- custom_components/fritzbox_tools/strings.json
optimizing config flow
Already fixed:
> Config flow opt

- custom_components/fritzbox_tools/manifest.json
- custom_components/fritzbox_tools/switch.py
simple switch to add call deflection. 
Related issue: #45
> add call deflection

- custom_components/fritzbox_tools/switch.py
> fix issue #66

- README.md
- custom_components/fritzbox_tools/.translations/de.json
- custom_components/fritzbox_tools/.translations/en.json
- custom_components/fritzbox_tools/__init__.py
- custom_components/fritzbox_tools/config_flow.py
- custom_components/fritzbox_tools/const.py
- custom_components/fritzbox_tools/strings.json
- custom_components/fritzbox_tools/switch.py
- info.md
adds another config step where user can decide which switches should be exposed
closes issue #61
> optimize config_flow by adding options

- custom_components/fritzbox_tools/switch.py
tested with multiple and single deflection configuration in Fritzbox
> fix issue #73 by rearangement of deflections response

- custom_components/fritzbox_tools/switch.py
> Fix issue #79 and #80

- README.md
- custom_components/fritzbox_tools/__init__.py
- custom_components/fritzbox_tools/const.py
- custom_components/fritzbox_tools/services.yaml
I tested (as appropriate):
Closes issue #107
What do you think @mammuth?
> add service to reboot fritzbox #107

- custom_components/fritzbox_tools/binary_sensor.py
Replace uptime attribute by last reconnect attribute in binary sensor. What do you think @mammuth?
Could you please test @chemelli74, @N1c093?
I tested (as appropriate):
Closes issue #35, 
Closes issue #93 
Closes issue #114
> Last reconnect attribute

- custom_components/fritzbox_tools/binary_sensor.py
- custom_components/fritzbox_tools/switch.py
- dealing with errors regarding repeaters
- warning about port range error in #75
I tested (as appropriate):
Closes issue #124
> Fix for repeaters

- custom_components/fritzbox_tools/manifest.json
Adds version attribute to manifest file as required by HA
Closes issue #146
> Add version to manifest

- custom_components/fritzbox_tools/binary_sensor.py
> Clean up part 2 - binary_sensor

- custom_components/fritzbox_tools/switch.py
> Clean up part 4 - switch

- custom_components/fritzbox_tools/services.yaml
> Clean up part 5 - services

- custom_components/fritzbox_tools/config_flow.py
> Clean up part 3 - config_flow

- custom_components/fritzbox_tools/__init__.py
- custom_components/fritzbox_tools/const.py
> Clean up part 1 - __init__

- custom_components/fritzbox_tools/__init__.py
- custom_components/fritzbox_tools/binary_sensor.py
- custom_components/fritzbox_tools/common.py
- custom_components/fritzbox_tools/config_flow.py
- custom_components/fritzbox_tools/switch.py
Just a small reorg of the code preparatory to the next activities
> Small reorg of code

- custom_components/fritzbox_tools/__init__.py
- custom_components/fritzbox_tools/manifest.json
I tested (as appropriate):
Closes issue #xxx
> skip config, print error and update dependencies
